<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="common_properties1.xacro"/>
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="1"/>
    <xacro:property name="base_height" value="0.05"/>

    <xacro:property name="neck_radius" value="0.05"/>
    <xacro:property name="neck_length" value="1.4"/>

    <xacro:property name="elbow_size" value="0.1"/>

    <xacro:property name="arm_radius" value="0.05"/>
    <xacro:property name="arm_length" value="0.75"/>

    <xacro:property name="head_size" value="0.4"/>

    <link name="base_footprint"/>

    <joint name="footprint_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="camera_base"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="camera_base">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height/2}" rpy="0 0 0" />
    </link>
    
     <joint name="base_neck_joint" type="fixed">
        <parent link="camera_base" />
        <child link="camera_neck" />
        <origin xyz="0 ${-base_width/3} ${base_height}" rpy="0 0 0"/>
    </joint>

    <link name="camera_neck">
        <visual>
            <geometry>
                <cylinder radius="${neck_radius}" length="${neck_length}" />
            </geometry>
            <origin xyz="0 0 ${neck_length/2}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${neck_radius}" length="${neck_length}" />
            </geometry>
            <origin xyz="0 0 ${neck_length/2}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${neck_radius}" h="${neck_length}"
                                xyz="0 0 ${neck_length/2}" rpy="0 0 0" />
    </link>
    
    <joint name="neck_elbow_joint" type="fixed">
        <parent link="camera_neck" />
        <child link="camera_elbow" />
        <origin xyz="0 0 ${neck_length+(elbow_size/2)}" rpy="0 0 0"/>
    </joint>

    <link name="camera_elbow">
        <visual>
            <geometry>
                <box size="${elbow_size} ${elbow_size} ${elbow_size}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${elbow_size} ${elbow_size} ${elbow_size}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="10" l="${elbow_size}" w="${elbow_size}" h="${elbow_size}"
                           xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <joint name="elbow_arm_joint" type="fixed">
        <parent link="camera_elbow" />
        <child link="camera_arm" />
        <origin xyz="0 ${arm_radius} 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_arm">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 ${arm_length/2} 0" rpy="${pi/2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <origin xyz="0 ${arm_length/2} 0" rpy="${pi/2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${arm_radius}" h="${arm_length}"
                                xyz="0 ${arm_length/2} 0" rpy="${pi/2.0} 0 0"  />
    </link>

    <joint name="arm_head_joint" type="fixed">
        <parent link="camera_arm" />
        <child link="camera_head" />
        <origin xyz="0 ${arm_length} 0" rpy="0 0 0"/>
    </joint>

    <link name="camera_head">
        <visual>
            <geometry>
                <box size="${head_size} ${head_size} ${head_size}"/>
            </geometry>
            <origin xyz="0 ${head_size/2} 0" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${head_size} ${head_size} ${head_size}"/>
            </geometry>
            <origin xyz="0 ${head_size/2} 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1" l="${head_size}" w="${head_size}" h="${head_size}"
                           xyz="0 ${head_size/2} 0" rpy="0 0 0"/>
    </link>

</robot>
